CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'outputs'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 5

DATASET:
  DATASET: railways_5classes
  ROOT: data/
  TEST_SET: 'list/railways_5classes/val.lst'
  TRAIN_SET: 'list/railways_5classes/train.lst'
  NUM_CLASSES: 6
MODEL:
  NAME: pidnet_large
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_L_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 720
  - 720
  BASE_SIZE: 1280
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: -100
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 1280
  - 720
  BASE_SIZE: 1280
  BATCH_SIZE_PER_GPU: 8
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
